[package]
name = "api"
version = "0.1.0"
authors = ["David La Chasse <david.lachasse@gmail.com>", "Chris Dieringer <christopher.dieringer+rad.dude@gmail>"]

[dependencies]
futures = "0.1.17"
hyper = "0.11.13"
serde_json = "1.0.9"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
tokio-core = "0.1"
