[package]
name = "api"
version = "0.1.0"
authors = ["David La Chasse <david.lachasse@gmail.com>", "Chris Dieringer <christopher.dieringer+rad.dude@gmail>"]

[dependencies]
futures = "*"
hyper = "*"
lazy_static = "*"
json  = "*"
rocket = "*"
rocket_codegen = "*"
tokio-core = "*"
