[package]
name = "api"
version = "0.2.0"
authors = ["David La Chasse <david.lachasse@gmail.com>", "Chris Dieringer <christopher.dieringer+rad.dude@gmail>"]

[dependencies]
futures = "0.1.17"
serde_json = "1.0.9"
actix = "0.5"
log = "0.4.1"
actix-web = "0.5.6"
